// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:4b5f61a6-6d26-465b-acc0-775c3c3dcc31',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'fitness-hosting-mobilehub-746495429',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1jq4e2kncropu.cloudfront.net',
    'aws_mobile_analytics_app_id': 'cb44056464744a338fa8a8d7430075b5',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'da236dbb-1b18-11e8-b7ec-1579a7b87ac8',
    'aws_project_name': 'fitness-2018-02-26-12-16-53',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'fitness-mobilehub-746495429',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_3BHgUYXE5',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '4rekuou1pctsgroqi2b0iqj9f',
}

export default awsmobile;
